# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podinate < Formula
  desc "Podinate - Declarative Kubernetes for developers"
  homepage "https://www.podinate.com"
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/podinate/podinate/releases/download/v0.0.8/podinate_Darwin_x86_64.tar.gz"
      sha256 "ddc390cfe183993967dbd360e7f147006304b490862f6ac3375a166886c05345"

      def install
        bin.install "podinate"
        bash_completion.install "completions/podinate.bash" => "podinate"
        zsh_completion.install "completions/podinate.zsh" => "_podinate"
        fish_completion.install "completions/podinate.fish"
      end
    end
    on_arm do
      url "https://github.com/podinate/podinate/releases/download/v0.0.8/podinate_Darwin_arm64.tar.gz"
      sha256 "b66d807ceed6952f7a5574c092683928c45d7b2010b4e09ce0473a2fa2205655"

      def install
        bin.install "podinate"
        bash_completion.install "completions/podinate.bash" => "podinate"
        zsh_completion.install "completions/podinate.zsh" => "_podinate"
        fish_completion.install "completions/podinate.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/podinate/podinate/releases/download/v0.0.8/podinate_Linux_x86_64.tar.gz"
        sha256 "f2c845104df2fe5542b2c6bdfc2a7fc79ee6d4d9155fb2278f8e328e017d36f4"

        def install
          bin.install "podinate"
          bash_completion.install "completions/podinate.bash" => "podinate"
          zsh_completion.install "completions/podinate.zsh" => "_podinate"
          fish_completion.install "completions/podinate.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/podinate/podinate/releases/download/v0.0.8/podinate_Linux_arm64.tar.gz"
        sha256 "3784524c65684d4ba6cc0f47425ca3e257cfddb9141282aa8bb989765a600b4c"

        def install
          bin.install "podinate"
          bash_completion.install "completions/podinate.bash" => "podinate"
          zsh_completion.install "completions/podinate.zsh" => "_podinate"
          fish_completion.install "completions/podinate.fish"
        end
      end
    end
  end
end
